# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['exe.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    Tree('data\\img\\test\\RC',prefix='data\\img\\test\\RC'),
    Tree('data\\img\\test\\RD',prefix='data\\img\\test\\RD'),
    Tree('data\\img\\test\\RU',prefix='data\\img\\test\\RU'),
    Tree('data\\img\\test\\LC',prefix='data\\img\\test\\LC'),
    Tree('data\\img\\test\\LD',prefix='data\\img\\test\\LD'),
    Tree('data\\img\\test\\LU',prefix='data\\img\\test\\LU'),
    Tree('data\\img\\test\\CC',prefix='data\\img\\test\\CC'),
    Tree('data\\img\\test\\CD',prefix='data\\img\\test\\CD'),
    Tree('data\\img\\test\\COMPASS',prefix='data\\img\\test\\COMPASS'),
    Tree('data\\img\\test\\CU',prefix='data\\img\\test\\CU'),
    Tree('data\\img\\test\\PATH',prefix='data\\img\\test\\PATH'),
    Tree('data\\img\\test\\WALL',prefix='data\\img\\test\\WALL'),
    Tree('data\\img\\test\\PLAYER',prefix='data\\img\\test\\PLAYER'),
    Tree('data\\img\\test\\FLAME',prefix='data\\img\\test\\FLAME'),
    Tree('data\\img\\test\\ACTION',prefix='data\\img\\test\\ACTION'),
    Tree('data\\img\\test\\BOARD_M',prefix='data\\img\\test\\BOARD_M'),
    Tree('data\\img\\test\\BOARD_S',prefix='data\\img\\test\\BOARD_S'),
    Tree('data\\img\\test\\BOX',prefix='data\\img\\test\\BOX'),
    Tree('data\\img\\test\\BOX_TAG',prefix='data\\img\\test\\BOX_TAG'),
    Tree('data\\img\\test\\ITEM',prefix='data\\img\\test\\ITEM'),
    Tree('data\\img\\test\\TEXT3',prefix='data\\img\\test\\TEXT3'),
    Tree('data\\img\\test\\TEXT5',prefix='data\\img\\test\\TEXT5'),
    Tree('data\\img\\test\\TEXT6',prefix='data\\img\\test\\TEXT6'),
    Tree('data\\img\\common\\BUTTON',prefix='data\\img\\common\\BUTTON'),
    Tree('data\\img\\config\\CONFIG',prefix='data\\img\\config\\CONFIG'),
    Tree('data\\img\\config\\CONFIG_BUTTON',prefix='data\\img\\config\\CONFIG_BUTTON'),
    Tree('data\\img\\config\\SET_BUTTON',prefix='data\\img\\config\\SET_BUTTON'),
    Tree('data\\img\\end\\END',prefix='data\\img\\end\\END'),
    Tree('data\\img\\home\\HOME',prefix='data\\img\\home\\HOME'),
    Tree('data\\img\\save\\SAVE',prefix='data\\img\\save\\SAVE'),
    Tree('data\\img\\save\\LIST',prefix='data\\img\\save\\LIST'),
    Tree('data\\img\\save\\SAVE_BUTTON',prefix='data\\img\\save\\SAVE_BUTTON'),
    Tree('data\\fonts',prefix='data\\fonts'),
    Tree('data\\mp3\\common\\CLICK',prefix='data\\mp3\\common\\CLICK'),
    Tree('data\\mp3\\common\\TEST',prefix='data\\mp3\\common\\TEST'),
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='game',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
